services:
  agent-gateway-krakend:
    build:
      context: .
      dockerfile: Dockerfile
    image: agent-gateway-krakend
    ports:
      - "10000:10000"
    volumes:
      - ./local/krakend.json:/etc/krakend/krakend.json:ro

  mock-agent:
    image: ghcr.io/agentic-layer/mock-agent:0.6
    ports:
      - "8000:8000"
    volumes:
      - ./local/wiremock:/home/wiremock/mappings:ro
