name: Check
on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:

jobs:
  test-plugins:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0 # required to fetch all history for all branches and tags

      - name: 'Setup Go'
        uses: 'actions/setup-go@v5'
        with:
          go-version-file: 'go/go.mod'

      - name: 'Test Plugins'
        working-directory: go
        run: |
          make test

      - name: 'Build Plugins'
        working-directory: go
        run: |
          make plugins

  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0 # required to fetch all history for all branches and tags

      - name: 'Docker Build'
        run: |
          make image
